### ISSUE TITLE
Webpack uglify

### ISSUE THREAD

**Issue by tushar-1health** [NathanaelA/nativescript-localstorage#10] opened 2017-06-14 09:19 UTC
Hello,

Webpack without uglify works fine. However, with --uglify flag it fails with following error.

```
ERROR in bundle.js from UglifyJs
Unexpected token: name (localStorageData) [bundle.js:73561,8]
```

**Comment by EddyVerbruggen** [comment] 2017-07-04 16:25
Yep, same here. Can be fixed by replacing all `let`'s by `var`'s in `localstorage.js`. I just forked this repo and changed that. Can do a PR if yall think this is the best solution.

**Comment by NathanaelA** [comment] 2017-07-04 17:09
The issue is that Uglify didn't support ES6.  https://github.com/mishoo/UglifyJS2/issues/448
The newer version Uglify-es supports ES6 but NativeScript Webpack version currently doesn't supported the Uglify-es yet.   At the point NativeScript and WebPack catch up; ES6 code will then work fine.

I'm not really keen on downgrading ES6 code to older ES5 code; seems like a big step backwards.

**Comment by EddyVerbruggen** [comment] 2017-07-04 17:32
I understand, no worries.

@tushar-1health be welcome to use my fork of this nice plugin and switch back to this one whenever ES6 is supported.

**Comment by jibon57** [comment] 2017-08-14 08:05
Yes, @EddyVerbruggen . I have solved this here: https://github.com/NathanaelA/nativescript-localstorage/pull/12

**Comment by Guatom** [comment] 2017-09-11 18:47
Hey guys! I've been having this problem with several other plugins and I agree with @NathanaelA that downgrading the source code just for the sake of Uglify is not a good option.

I ended up adding `babel-loader` only for these ES6 plugins, something like this in `webpack.config.js`:
```javascript
// Transpile ES6+ files
{
  test: /\.js$/,
    loader: "babel-loader",
      include: [
        resolve(__dirname, 'node_modules/nativescript-sms-inbox'),
        resolve('nativescript-contacts-lite'),
      ],
        query: {
    presets: [
      [
        "es2015",
        {
          "targets": {
            "uglify": false
          }
        }
      ]
    ]
  }
}
```
Hope this helps.

**Comment by NathanaelA** [comment] 2017-09-11 19:28
@Guatom - Excellent solution, thanks for commenting.

**Comment by bfv** [comment] 2017-10-20 09:08
If you upgrade UglifyJS to version 3 ES6 is supported, see: https://github.com/NativeScript/nativescript-angular/issues/1011 (the sis0k0 post). Worked for me to webpack/ugilfy a project with this plugin.

**Comment by rigoparis** [comment] 2018-05-24 23:09
This happens while using {N}-Vue's template

[https://github.com/nativescript-vue/vue-cli-template](https://github.com/nativescript-vue/vue-cli-template)

**Comment by NathanaelA** [comment] 2018-05-25 00:09
@rigoparis - Can you tell me which version of Webpack you are using; the uglify issue should have been fixed a while back by the NativeScript team when they started using v1.x of the uglify plugin.

**Comment by samtgarson** [comment] 2018-05-27 12:10
@NathanaelA I believe the {N}-Vue template has not yet been updated to a later version of Webpack.

@rigoparis I've solved this temporarily using the quick solution in [this comment](https://github.com/joeeames/WebpackFundamentalsCourse/issues/3#issuecomment-344413628)—basically using `require('uglifyjs-webpack-plugin)` instead of `webpack.optimize.UglifyJsPlugin`

**Comment by NathanaelA** [comment] 2018-05-27 16:23
@samtgarson - Sam thanks for the status update; I would have expected that Igor was using the latest version of the NS webpack in the Vue stuff...

**Comment by NathanaelA** [comment] 2018-09-13 05:12
This should now be fixed; NS-Vue should be using the latest Webpack.  :grinning:

**Closed as completed by NathanaelA** 2018-09-13 05:12 UTC
